FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements-base.txt requirements-bot.txt ./
RUN pip install --no-cache-dir -r requirements-bot.txt

COPY app ./app
COPY main.py ./main.py

CMD ["python", "main.py"]
